// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using afterwork.data;

namespace afterwork.data.Migrations
{
    [DbContext(typeof(AfterWorkDbContext))]
    [Migration("20190613193451_EventsToMeetup")]
    partial class EventsToMeetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("afterwork.model.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("afterwork.model.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("afterwork.model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("afterwork.model.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("LocationId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("afterwork.model.MeetUp", b =>
                {
                    b.Property<int>("MeetUpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<int>("Complexity");

                    b.Property<int?>("CountryId");

                    b.Property<int?>("CreatorUserId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndTime");

                    b.Property<int?>("GatheringSpotLocationId");

                    b.Property<bool>("IsConfirmed");

                    b.Property<bool>("IsPrivate");

                    b.Property<int?>("MeetUpImageId");

                    b.Property<int?>("MeetUpPlaceLocationId");

                    b.Property<int>("MeetUpType");

                    b.Property<double>("MinimalBudget");

                    b.Property<string>("Name");

                    b.Property<int>("ParticipantLimit");

                    b.Property<string>("Rating");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("MeetUpId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("GatheringSpotLocationId");

                    b.HasIndex("MeetUpImageId");

                    b.HasIndex("MeetUpPlaceLocationId");

                    b.ToTable("MeetUps");
                });

            modelBuilder.Entity("afterwork.model.MeetUpAdministrator", b =>
                {
                    b.Property<int>("MeetUpId");

                    b.Property<int>("UserId");

                    b.HasKey("MeetUpId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetUpAdministrator");
                });

            modelBuilder.Entity("afterwork.model.MeetUpDateTimeVoter", b =>
                {
                    b.Property<int>("MeetUpDateTimeVoterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PropositionForMeetUpDateTimeId");

                    b.Property<int>("PropositionForMeetUptDateTimeId");

                    b.Property<int>("UserId");

                    b.HasKey("MeetUpDateTimeVoterId");

                    b.HasIndex("PropositionForMeetUpDateTimeId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetUpDateTimeVoter");
                });

            modelBuilder.Entity("afterwork.model.MeetUpImage", b =>
                {
                    b.Property<int>("MeetUpImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path");

                    b.HasKey("MeetUpImageId");

                    b.ToTable("MeetUpImages");
                });

            modelBuilder.Entity("afterwork.model.MeetUpPartisipant", b =>
                {
                    b.Property<int>("MeetUpId");

                    b.Property<int>("UserId");

                    b.HasKey("MeetUpId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MeetUpPartisipant");
                });

            modelBuilder.Entity("afterwork.model.PropositionForMeetUpDateTime", b =>
                {
                    b.Property<int>("PropositionForMeetUpDateTimeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MeetUpId");

                    b.Property<DateTime>("ProposedDateTime");

                    b.Property<int?>("PropositionCreatorUserId");

                    b.Property<int>("VoicesCount");

                    b.HasKey("PropositionForMeetUpDateTimeId");

                    b.HasIndex("MeetUpId");

                    b.HasIndex("PropositionCreatorUserId");

                    b.ToTable("PropositionForMeetUpDateTime");
                });

            modelBuilder.Entity("afterwork.model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber");

                    b.Property<string>("Email");

                    b.Property<int?>("GroupId");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("afterwork.model.MeetUp", b =>
                {
                    b.HasOne("afterwork.model.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("afterwork.model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("afterwork.model.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("afterwork.model.Location", "GatheringSpot")
                        .WithMany()
                        .HasForeignKey("GatheringSpotLocationId");

                    b.HasOne("afterwork.model.MeetUpImage", "MeetUpImage")
                        .WithMany()
                        .HasForeignKey("MeetUpImageId");

                    b.HasOne("afterwork.model.Location", "MeetUpPlace")
                        .WithMany()
                        .HasForeignKey("MeetUpPlaceLocationId");
                });

            modelBuilder.Entity("afterwork.model.MeetUpAdministrator", b =>
                {
                    b.HasOne("afterwork.model.MeetUp", "MeetUp")
                        .WithMany("MeetUpAdministrator")
                        .HasForeignKey("MeetUpId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("afterwork.model.User", "User")
                        .WithMany("MeetUpAdministrator")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("afterwork.model.MeetUpDateTimeVoter", b =>
                {
                    b.HasOne("afterwork.model.PropositionForMeetUpDateTime", "PropositionForMeetUpDateTime")
                        .WithMany("MeetUpDateTimeVoter")
                        .HasForeignKey("PropositionForMeetUpDateTimeId");

                    b.HasOne("afterwork.model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("afterwork.model.MeetUpPartisipant", b =>
                {
                    b.HasOne("afterwork.model.MeetUp", "MeetUp")
                        .WithMany("MeetUpPartisipant")
                        .HasForeignKey("MeetUpId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("afterwork.model.User", "User")
                        .WithMany("MeetUpPartisipant")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("afterwork.model.PropositionForMeetUpDateTime", b =>
                {
                    b.HasOne("afterwork.model.MeetUp", "MeetUp")
                        .WithMany("PropositionForMeetUpDateTime")
                        .HasForeignKey("MeetUpId");

                    b.HasOne("afterwork.model.User", "PropositionCreator")
                        .WithMany()
                        .HasForeignKey("PropositionCreatorUserId");
                });

            modelBuilder.Entity("afterwork.model.User", b =>
                {
                    b.HasOne("afterwork.model.Group")
                        .WithMany("Participants")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
